on:
  # push:
    # branches: [ main ]
  schedule:
    - cron: '1 5 * * *'     # https://crontab.guru/

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: cache node dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules  # 需要缓存的文件的路径
          key: ${{runner.os}}-npm-caches-${{ hashFiles('package-lock.json') }}
          # key: 缓存文件的标识


      - name: install dependecies
        # 判断是否 命中缓存 
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install  

      # - name: node run file
      #   run: node schedule-readme.js
      - name: run script file
        id: script
        uses: actions/github-script@v5
        with: 
          result-encoding: string
          script: |
            const script = require('./schedule-readme.js')
            const changed = await script({github,context,core})
            return changed

      - name: check script result
        run: |
          echo The file changed ':' ${{ steps.script.outputs.result }}

      - name: commit and push
        if: ${{steps.script.outputs.result}} == 'true'
        run: |
          git config user.name 'hezhongjie'
          git config user.password 'hezhongjie1993'
          git config user.email 'hezhongjie132@163.com'
          git add README.md
          git commit -m "Github Action Auto Updated"
          git push


      # - name: git-change
      #   id: git_change
        # uses: collin-miller/git-changesets

      # - name: test
      #   run: |
      #     echo ${{steps.git_change.outputs.all}}
      #     echo ${{steps.git_change.outputs.added}}
      #     echo ${{steps.git_change.outputs.modified }}
      #     echo ${{steps.git_change.outputs.added_modified  }}


      

      # 如何  判断 git diff的返回值 ？